name: CI - Build & Push to GHCR 

on:
  push:
    branches: [ "main" ]

# Configura los permisos para el GITHUB_TOKEN predeterminado
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Usa el usuario actual de GitHub
          password: ${{ secrets.GITHUB_TOKEN }} # Usa el token predeterminado

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Contexto: usa la raíz del repositorio (donde está tu Dockerfile)
          context: . 
          # Archivo: especifica el Dockerfile en la raíz
          file: ./Dockerfile 
          push: true
          # Etiqueta: usa tu usuario y el nombre de tu repositorio actual (ej. servidor-app)
          tags: ghcr.io/AnthonyYuvaniTorresIzaguirre/servidor-app:latest